import {mkdir,cp,readFile,writeFile} from 'node:fs/promises';
// Compile the local modules to classic scripts so file:// needs no CORS
// exceptions or local server. Reject unsupported imports rather than silently
// producing a broken bundle when this small module graph changes.
const modules=['input','app'];
let bundle='/* Generated by scripts/build.mjs. Edit src/, then rebuild. */\n(async()=>{\n"use strict";\nconst modules=Object.create(null);\n';
for(const name of modules){
  let source=await readFile(`src/${name}.js`,'utf8');
  const names=[...source.matchAll(/^export\s+(?:async\s+)?(?:function|const)\s+(\w+)/gm)].map(m=>m[1]);
  source=source.replace(/^import\s+\{([^}]+)\}\s+from\s+['"]\.\/(\w+)\.js['"];?\s*$/gm,(_,bindings,dependency)=>{
    if(!modules.includes(dependency)||modules.indexOf(dependency)>=modules.indexOf(name))throw Error(`Unexpected dependency ${name} -> ${dependency}`);
    return `const {${bindings}}=modules[${JSON.stringify(dependency)}];`;
  }).replace(/^export\s+/gm,'');
  if(/^\s*(?:import|export)\s/m.test(source))throw Error(`Unsupported module syntax in ${name}`);
  bundle+=`modules[${JSON.stringify(name)}]=${name==='app'?'await (async()=>{':'(()=>{'}\n${source}\nreturn {${names.join(',')}};\n})();\n`;
}
bundle+='})().catch(error=>{console.error(error);const box=document.querySelector("#output");if(box)box.textContent="規劃程式啟動失敗，請重新解壓縮完整資料夾後再開啟 index.html。";});\n';
await writeFile('public/app.bundle.js',bundle);
await mkdir('web-dist',{recursive:true});
for(const file of ['index.html','services.html','style.css','config.js','app.bundle.js'])await cp('public/'+file,'web-dist/'+file);
console.log('Built web-only GitHub Pages files in web-dist/');
